### ISSUE TITLE
UI: Authenticate Register and Login

### ISSUE THREAD

**Issue by forrestfiller** [ryanab/fileshare#2]
Setup the UI for the Authenticate view component
===

- Integrate ```authenticate``` component into the ```Home``` and ```StaticProfile``` layouts

**Comment by forrestfiller** [comment]
@ryanab @jdrichardstech @robungar I recall we discussed....popping this up into the navbar in a dropdown menu? Or was there another integration we discussed? Let me know

**Comment by jdrichardstech** [comment]
I thought we decided to place a Login/Sign Up link in navbar...when clicked it would render the authenticate component on a seperate view/page...we used Twitter as the example.

**Comment by forrestfiller** [comment]
Yes. Thanks JD. I was trying to recall. Thanks

**Comment by ryanab** [comment]
@jdrichardstech @forrestfiller Either or is fine; I have account component back in the Home layout because I was working on those bugs from the merge conflict; but you can take it back out.

**Comment by forrestfiller** [comment]
Done.
![](http://i.giphy.com/nOrMCofRpdhmw.gif)
