### ISSUE TITLE
README Needed

### ISSUE THREAD

**Issue by forrestfiller** [ryanab/fileshare#4]
Draft a full README.md
===

- SPA's functionality
- Build Instructions
- Credits

**Comment by ryanab** [comment]
@forrestfiller can you work on the Readme?   I heard a rumor you are the Markdown expert

**Comment by forrestfiller** [comment]
Haha. I'll take a look later

**Comment by forrestfiller** [comment]
Done. (for now!)
- I just pushed my local edits in the **[readme branch](https://github.com/ryanab/fileshare/tree/readme)** up to the remote. Check it out, feel free to adjust. @ryanab @jdrichardstech @robungar 
- Not sure if you want to merge yet, as we don't have firebase instructions in the readme, and folks may wish to edit for style and (potentially) grammar.

**Comment by ryanab** [comment]
@forrestfiller can you please edit the README.md just in the Github editor and I believe it should merge right in.  Somehow I messed up the numbers/bullets/etc.  Thanks.

**Comment by forrestfiller** [comment]
Will do. I'll complete and merge into master + delete branch before I see you tonight. 

Forrest Filler

**Comment by ryanab** [comment]
By 12:30

**Comment by forrestfiller** [comment]
😂 no chance that will happen by 1230

**Comment by forrestfiller** [comment]
[Merged, closing issue #4 with this commit](https://github.com/ryanab/fileshare/tree/0eed153a356697e8363ee95c5b7470498ce12a11)
