### ISSUE TITLE
Account: actions is not defined

### ISSUE THREAD

**Issue by forrestfiller** [ryanab/fileshare#5]
When loading the home page, I get the following error. Perhaps it is only me on my branch. Nonetheless have a look:
![screen shot 2017-02-05 at 11 24 58](https://cloud.githubusercontent.com/assets/18606441/22627736/e936e338-eb95-11e6-957a-579b5a56f6ef.png)

- Perhaps since I am not logged in? Let me know.

**Comment by forrestfiller** [comment]
Well...I just added an import to the Account.js container and it worked: not sure if this was my fault or preexisting:
```import actions from '../../actions'```

**Comment by forrestfiller** [comment]
@ryanab please fix this on master and merge it in.

**Comment by ryanab** [comment]
@forrestfiller fixed thanks, also an issue from the merge but now resolved and pushed to master
