### ISSUE TITLE
Authentication: On Registration or Login, Adjust UI to Show Updated State

### ISSUE THREAD

**Issue by forrestfiller** [ryanab/fileshare#6]
Update UI to reflect updated state of logged-in/registered user
===

- When I try to register from the index page as a new user, there is no change to the UI to give me feedback on my success or failure.
    - I do get a delightful console log in my web console and console log on my backend terminal:
![screen shot 2017-02-05 at 11 47 43](https://cloud.githubusercontent.com/assets/18606441/22627953/915f1d66-eb99-11e6-85e6-4e86d64b5586.png)
and my quick check to the ```/api/profile``` and ```/account/currentuser``` show me as in my local backend and as a current logged in user.

- Not sure if this is on me or someone else on the team, please advise.

**Comment by ryanab** [comment]
@forrestfiller can you clone the GitHub repo in a separate folder on your desktop so it does not interfere with your local version/branch and let me know if issue still exista

**Comment by forrestfiller** [comment]
@ryanab  you are referring to the bug I filed, not this? Right? Or is this also fixed?

**Comment by ryanab** [comment]
@forrestfiller this has been fixed.  Some how when we merged the branches we lost some work in the account component.
